/*
 * Copyright (c) 2026 Adrien ARNAUD
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#version 460
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 64) in;

layout(set = 0, binding = 0) uniform sampler imageSampler;

layout(set = 0, binding = 1) buffer restrict writeonly Output { float values[]; }
outputBuffer;

layout(set = 0, binding = 2) uniform texture2D images[];

layout(push_constant) uniform PushConstants { uint count; }
params;

void main()
{
    const uint idx = gl_GlobalInvocationID.x;
    if(idx < params.count)
    {
        outputBuffer.values[idx]
            = texture(sampler2D(images[nonuniformEXT(idx)], imageSampler), vec2(0.5, 0.5)).x;
    }
}